---
- hosts: all
  tasks:
    - name: echo something
      debug:
        msg: "All is ok "
    - name: install mysql
      yum:
        pkg: { item }
      with_items:
      - mysql
      - mariadb
      - ruby
      - python
